### ISSUE TITLE
Handle '$' symbol in SQL string

### ISSUE THREAD

**Issue by alexkon** [alexkon/pretty-sql-sbt-plugin#22]
It looks when we have `$` symbol (Scala string interpolation) our plugin doesn't work in a proper way. We should fix it

**Comment by uditagrawal08** [comment]
hi @alexkon , i want to fix this problem can you assign this to me

**Comment by alexkon** [comment]
@uditagrawal08 
Hi Kumar!
Thanks for your help!
Yes, please do it 😎

**Comment by alexkon** [comment]
@koljahuang 
Kolja, could you please describe the place and the nature of the problem first, before to start resolving it
